@startuml SGCI Tabela Diário Anexo
!theme plain
skinparam linestyle orthopedic
left to right direction

entity "tb_diario_anexo" as tb_diario_anexo #f8ffd1{
  * id_anexo : int [PK] <<auto_increment>>
  --
  * diario_id : int [FK]
  * caminho_arquivo : varchar(255)
  nome_original : varchar(255)
'  * criado_em : datetime [DF: CURRENT_TIMESTAMP]
'  * atualizado_em : datetime [DF: CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP]
}

' Notas para índices internos
'note bottom of tb_diario_anexo
'  **Índices:**
'  * [KEY] fk_anexo_diario (diario_id)
'end note

' --- Definição da tabela externa ---
'entity "tb_diario_aula" as tb_diario_aula {}

' --- Relacionamento baseado na CONSTRAINT do SQL ---
'tb_diario_aula "1" -- "0..*" tb_diario_anexo : "fk_anexo_diario (CASCADE)"

@enduml