@startuml SGCI Tabela Matrícula
!theme plain
skinparam linestyle orthopedic
left to right direction

entity "tb_matricula" as tb_matricula #fccccc57{
  * id_matricula : int [PK] <<auto_increment>>
  --
  * aluno_id : int [FK]
  * turma_id : int [FK]
  * data_matricula : date
  status_matricula : enum('ativa','trancada','cancelada','concluida') [DF: 'ativa']
'  observacao : text
'  * ativo : tinyint(1) [DF: 1]
'  * criado_em : datetime [DF: CURRENT_TIMESTAMP]
'  * atualizado_em : datetime [DF: CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP]
'  deletado_em : datetime [DF: NULL]
}

' Notas para índices complexos e chaves únicas compostas
'note bottom of tb_matricula
'  **Chaves Únicas & Índices:**
'  * [UQ] uq_matricula_aluno_turma (aluno_id, turma_id)
'  * [KEY] fk_matricula_turma (turma_id)
'end note
' --- Tabelas Relacionadas (Definições para amarrar o DER) ---
'entity "tb_aluno" as tb_aluno {}
'entity "tb_turma" as tb_turma {}

' --- Relacionamentos baseados nas CONSTRAINTS do seu SQL ---
'tb_aluno "1" -- "0..*" tb_matricula : "fk_matricula_aluno (RESTRICT)"
'tb_turma "1" -- "0..*" tb_matricula : "fk_matricula_turma (RESTRICT)"

@enduml