@startuml SGCI Tabela Turma Dias
!theme plain
skinparam linestyle orthopedic
left to right direction

entity "tb_turma_dias" as tb_turma_dias #fccccc57{
  * id_turma_dia : int [PK] <<auto_increment>>
  --
  * turma_id : int [FK]
  * dia_semana : enum('dom','seg','ter','qua','qui','sex','sab')
'  * ativo : tinyint(1) [DF: 1]
'  * criado_em : datetime [DF: CURRENT_TIMESTAMP]
'  * atualizado_em : datetime [DF: CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP]
'  deletado_em : datetime [DF: NULL]
}

' Notas para chaves únicas compostas
'note bottom of tb_turma_dias
'  **Chaves Únicas & Índices:**
'  * [UQ] ux_turma_dia (turma_id, dia_semana)
'end note

' --- Definição da tabela externa para amarração ---
'entity "tb_turma" as tb_turma {}

' --- Relacionamento baseado na CONSTRAINT do seu SQL ---
'tb_turma "1" -- "0..*" tb_turma_dias : "fk_turmadias_turma (CASCADE)"

@enduml